Решение 2 задачи 1 модуля Meetup Page Draft
js-tasks-ru/vue-20200925-2_udovik-aleksey pull request #5
Opened 2020-11-06 16:02 UTC by Pushkinson

В комментариях script.js оставил вопрос, продублирую здесь:
57 строка:
не совсем понял почему так происходит:

если rawMeetups: [], - никаких ошибок не вылетает, но при обновлении страницы проскакивает шаблонная верстка (без Vue.js);
если оставляю rawMeetups: null, - выскакивают ошибки, похожие на те, что были в вебинаре (2 занятие), но с отрисовкой при обновлении страницы все в порядке;
тесты проходят успешно в обоих случаях

2020-11-06 16:50 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Meetup Page Draft
+ Задача добавлена, но требует ручной проверки
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-11-08 09:34 UTC, ShGKme requested changes
Требуется как минимум избавиться от XSS. Это серьёзная проблема в безопасности

2020-11-08 09:34 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +                <h5 class="meetup-agenda__title" v-html="item.title ? item.title : $options.agendaItemTitles[item.type]"></h5>
v-html выведет значение как html без какого-либо экранирования. Это потенциальный XSS.

Любой пользователь может сделать свой митап с любым заголовком, в том числе использовать там теги или внедрять скрипты. С v-html получится серьёзная дыра в безопасности.

Правильнее использовать обычные выражения `{{ value }}`.

Если так было сделано из-за `<s>` в названии одного из докладов, то это оригинальное название: [https://vueconf.us/schedule/](https://vueconf.us/schedule/). `All you need is <s>love</s> Apollo Client`

Но наличие таких названий не должно приводить к XSS

2020-11-08 09:34 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +              <time datetime="2020-02-31">{{ meetup.localeDate }}</time>
У элемента `time` есть ещё атрибут `datetime`

2020-11-08 09:34 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
> +    // тесты проходят успешно в обоих случаях
С `null` вылезают ошибки, потому что у null нет всех тех свойств, которые выводятся в шаблоне.
Нельзя вывести `meetup.title`, если `meetup === null`.

С `[]` таких ошибок в данном случае нет, потому что `[].title` просто равен `undefined`.
Но:
1. Это совершенно не логично, не понятно, почему изначально переменная, в которой должен быть **объект** с описанием митапа, имеет значением пустой массив.
2. Это бы привело к другим ошибкам, например, если бы была работа с более глубокими свойствами, например, если бы computed обновлял `meetup.agenda`.
3. Это уже приводит к ошибкам, потому что на время загрузки страница выводится очень сломанной. Вёрстка ломается, когда отсутствуют те тексты, которые ожидается, что есть всегда.

Чтобы ошибок не было, требуется просто в шаблоне на некотором "всё оборачивающем" (но не корневым) элементе установить директиву `v-if` на meetup, и не выводить страница с описанием митапа, пока не пришли данные митапа.

2020-11-08 14:06 UTC, Pushkinson commented on 01-basics/02-MeetupPageDraft/index.html
> +                <h5 class="meetup-agenda__title" v-html="item.title ? item.title : $options.agendaItemTitles[item.type]"></h5>
Да, изначально подумал, что <s> необходимо учесть при отрисовке названия. Убрал v-html, добавил экранирование.

2020-11-08 14:09 UTC, Pushkinson commented on 01-basics/02-MeetupPageDraft/index.html
> +              <time datetime="2020-02-31">{{ meetup.localeDate }}</time>
Спасибо! Упустил этот момент. Поправил

2020-11-08 14:11 UTC, Pushkinson commented on 01-basics/02-MeetupPageDraft/script.js
> +    // тесты проходят успешно в обоих случаях
Спасибо большое за объяснение! Добавил условие в оборачивающем элементе.

2020-11-08 14:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-11-08 17:04 UTC, ShGKme requested changes
Не все проблемы исправлены... Главная проблема - XSS

2020-11-08 17:04 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +<div id="app" v-cloak v-if="meetup !== null">
На корневой элемент нельзя ставить `v-if`...

2020-11-15 17:28 UTC, ShGKme approved these changes
Видимо, я смотрел решение, когда только первый коммит был, либо что-то не обновил...

Задача принята 👍
Прошу прощения! Пишите, если мои комментарии не понятны или кажутся неверными :)

2020-11-15 17:28 UTC, merged

2020-11-15 17:45 UTC, Pushkinson commented
Спасибо за разъяснения! Я уже сам собирался написать, уже все что можно про XSS прочитал, пытался понять, что не так :)